daniel-kulbe.de:
  script:
    - 'CI_DEPLOY_PATH="${DEPLOY_PATH}";CI_DEPLOY_LOG="${DEPLOY_LOG}";CI_DEPLOY_USER="${DEPLOY_USER}"'
    - 'sudo /var/www/hostLC/priv/deploy.sh'
  type: deploy
  only:
    - tags

poppetsphere.de:
  script:
    - 'CI_DEPLOY_PATH="${DEPLOY2_PATH}";CI_DEPLOY_LOG="${DEPLOY2_LOG}";CI_DEPLOY_USER="${DEPLOY2_USER}"'
    - 'sudo /var/www/hostLC/priv/deploy.sh'
  type: deploy
  only:
    - tags